---

variables:
  MM_BUILDER_IMAGE: "electronuserland/builder:wine-mono"
  MM_PACKAGE: "yes"  
  MM_PACKAGE_CMD: "package-debian"
  MM_BUILD_DIR: "/build/linux"

include:
  - project: mattermost/ci/desktop
    ref: chore/dops-794
    file: private.yml


