// Copyright (c) 2016-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

/**
 * Optional demo run: writes PNGs for PR / automation reports when MM_TEST_* is set.
 * Skips in CI or local runs without server credentials. Not a product regression test.
 */
import * as fs from 'fs/promises';
import * as path from 'path';

import {test, expect} from '../../fixtures/index';
import {demoMattermostConfig, sourceRootDir} from '../../helpers/config';
import {loginToMattermost, waitForLoggedIn} from '../../helpers/login';

const outDir = path.join(sourceRootDir, 'docs', 'qa-artifacts', 'pr-3773-demo');

test.describe('qa demo — exploration screenshots (optional)', () => {
    test.use({appConfig: demoMattermostConfig});

    test('capture main window and server view after login', {
        tag: ['@qa-demo', '@all'],
    }, async ({electronApp, mainWindow, serverMap}, testInfo) => {
        test.skip(
            !process.env.MM_TEST_SERVER_URL || !process.env.MM_TEST_USER_NAME || !process.env.MM_TEST_PASSWORD,
            'Set MM_TEST_SERVER_URL, MM_TEST_USER_NAME, MM_TEST_PASSWORD to generate demo PNGs',
        );

        const entry = serverMap.example?.[0];
        const serverWin = entry?.win;
        const webContentsId = entry?.webContentsId;
        expect(serverWin, 'server view for configured Mattermost server').toBeDefined();
        expect(webContentsId, 'webContentsId for server view').toBeDefined();

        await loginToMattermost(electronApp, serverWin!);
        await waitForLoggedIn(electronApp, mainWindow, 90_000);

        await fs.mkdir(outDir, {recursive: true});

        await mainWindow.screenshot({path: path.join(outDir, '01-main-window.png'), fullPage: true});

        const sidebarOk = await serverWin!.waitForSelector('#sidebarItem_town-square, [data-testid="town-square"]', {
            timeout: 30_000,
        }).then(() => true).catch(() => false);
        if (sidebarOk) {
            // Channel list / team sidebar visible
            await new Promise((r) => setTimeout(r, 500));
        }

        const pngBytes = await electronApp.evaluate(({webContents}, id: number) => {
            return new Promise<number[] | null>((resolve) => {
                const wc = webContents.fromId(id);
                if (!wc || wc.isDestroyed()) {
                    resolve(null);
                    return;
                }
                wc.capturePage().then((image) => {
                    resolve(Array.from(image.toPNG()));
                }).catch(() => resolve(null));
            });
        }, webContentsId!);

        if (pngBytes?.length) {
            await fs.writeFile(path.join(outDir, '02-server-webcontents.png'), Buffer.from(pngBytes));
        }

        await mainWindow.click('#newTabButton', {timeout: 15_000}).catch(() => {});
        await mainWindow.waitForTimeout(800);
        await mainWindow.screenshot({path: path.join(outDir, '03-after-new-tab-click.png'), fullPage: true});

        await fs.writeFile(
            path.join(outDir, 'README.md'),
            [
                '# PR #3773 — demo exploration screenshots',
                '',
                'Generated by `e2e/specs/qa_demo/pr_exploration_screenshots.test.ts` when `MM_TEST_SERVER_URL`,',
                '`MM_TEST_USER_NAME`, and `MM_TEST_PASSWORD` are set (e.g. Matterwick test server).',
                '',
                '| File | Description |',
                '|------|----------------|',
                '| `01-main-window.png` | Application wrapper (tab bar, chrome) |',
                '| `02-server-webcontents.png` | Embedded Mattermost server view (`capturePage`) |',
                '| `03-after-new-tab-click.png` | Wrapper after **New tab** interaction |',
                '',
                `Last generated: ${new Date().toISOString()} (Playwright run \`${testInfo.title}\`)`,
                '',
            ].join('\n'),
            'utf8',
        );

        expect(pngBytes?.length, 'server view capture should produce PNG bytes').toBeTruthy();
    });
});
