name: Bug report
description: Create a report about an issue you found in the Mattermost Desktop App
title: "[Bug]: "
labels: "Type/Bug"
body:
- type: markdown
  attributes:
    value: |
      ## STOP! Before you file a bug report
      Check that the issue is truly a Desktop App issue and not an issue with our Web App. The Desktop App makes use of the Mattermost Web App to render Mattermost. This repository is for issues with the Desktop App wrapper.
      You can do this by going to your web browser (preferably Chrome) and attempting to reproduce the issue there.
      If it does, the issue should be reported to the [main Mattermost repository](https://github.com/mattermost/mattermost/issues).
- type: checkboxes
  attributes:
    label: Checks before filing an issue
    description: Please ensure you can confirm the following
    options:
      - label: This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
        required: true
      - label: I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
        required: true
      - label: "This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16."
        required: true
      - label: "This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/."
        required: true
      - label: This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
        required: true
      - label: I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).
        required: true
- type: input
  attributes:
    label: Mattermost Desktop Version 
    description: |
      What version of the Desktop App are you using? You can find it by going to [Help] > [Version Number].
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: |
      What operating system does this issue occur on? Please include the distribution name (if necessary) and architecture.

      Examples:
      - Windows 10 x64
      - macOS Ventura 13.2 Apple Silicon
      - Ubuntu Linux 22.04 LTS x64
  validations:
    required: true
- type: input
  attributes:
    label: Mattermost Server Version
    description: |
      Which version of the Mattermost Server did this occur on?
      You can find your Mattermost Server version by [Mattermost Menu] > [About Mattermost], where [Mattermost Menu] can be accessed by clicking on the grid in the top-left corner.
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Include a clear description of the steps taken to reproduce this issue.
      It is also helpful to attach a screenshot or video if applicable.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: Include a clear description of what you expect to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Observed behavior
    description: Include a clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Log Output
    description: Please include output from the log files. You can find the location of the log files by going to [Help] > [Show logs].
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: If you have anything else to add to the ticket, you may do so here. 
