---

title: "Mattermost Desktop"
copyright: "© 2016-2017 Mattermost, Inc.  All Rights Reserved.  See LICENSE.txt for license information."
description: "This document includes a list of open source components used in Mattermost Desktop, including those that have been modified."
reviewers: 
  - mattermost/release-managers
  - mattermost/team-desktop
search:
  - "package.json"
additionalDependencies:
  - wix
includeDevDependencies: true
...
