name: Start Mattermost Server for Testing

on:
  workflow_dispatch:
  push:
    branches: 
        - master
        - e2e-jobs-with-server

jobs:
  start-server-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List workflows in private repo
        uses: actions/github-script@v6
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          script: |
            const workflows = await github.rest.actions.listRepoWorkflows({
                owner: 'mattermost',
                repo: 'delivery-platform',
            });
            core.info(`📂 Workflows found: ${workflows.data.workflows.map(w => w.path).join(', ')}`);

      - name: Start Server
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
        with:
          script: |
            try {
              // First verify the workflow exists
              const workflow = await github.rest.actions.getWorkflow({
                owner: 'mattermost',
                repo: 'delivery-platform',
                workflow_id: 'e2e-testing-with-desktop-servers.yml',
              });
              
              console.log(`Found workflow: ${workflow.data.path}`);

              // Then trigger it
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: 'mattermost',
                repo: 'delivery-platform',
                workflow_id: 'e2e-testing-with-desktop-servers.yml',
                ref: 'master',  // Try 'main' if this fails
              });

              console.log(`Triggered workflow run ID: ${response.status}`);
              return response.status;
            } catch (error) {
              console.error('Full error details:', error);
              core.setFailed(`Failed to trigger workflow. Ensure:
              1. The repo mattermost/delivery-platform exists
              2. The workflow e2e-testing-with-desktop-servers.yml exists
              3. You have permission to trigger workflows`);
              throw error;
            }