name: Snyk - Software Bill of Materials (SBOM)
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        type: string
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@a7b0a0fbb4c962f12f34f70563997636e49ac4ac
    secrets: inherit
    with:
      is_monorepo: false
      tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
