name: Snyk - Software Bill of Materials (SBOM)
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        type: string
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@2174576d3c65eb4db691bf09fd72246b59f331c8
    secrets: inherit
    with:
      is_monorepo: false
      tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
