name: Snyk - Software Bill of Materials (SBOM)
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@f6f5c197e88e322d57b00d64578fb8c03f993a9d
    secrets: inherit
    with:
      is_monorepo: false
