name: Snyk - Software Bill of Materials (SBOM)
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@97a61c0e3ee52b92b16054e5c60faaa870693476
    secrets: inherit
    with:
      is_monorepo: false
