name: Snyk - Software Bill of Materials (SBOM)
on:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@33b5c7edb191065996ee9f7ff20b608512b6d64e
    secrets: inherit
    with:
      is_monorepo: false
